#!/usr/bin/env bash
# generate_version.sh — Extract version from VERSION.txt and generate version.h
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VERSION_FILE="$SCRIPT_DIR/../VERSION.txt"
OUTPUT_FILE="$SCRIPT_DIR/../src/DAWCast/version.h"

if [ ! -f "$VERSION_FILE" ]; then
    echo "ERROR: VERSION.txt not found at $VERSION_FILE"
    exit 1
fi

VERSION=$(cat "$VERSION_FILE" | tr -d '[:space:]')
MAJOR=$(echo "$VERSION" | cut -d. -f1)
MINOR=$(echo "$VERSION" | cut -d. -f2)
PATCH=$(echo "$VERSION" | cut -d. -f3 | cut -d- -f1)
SUFFIX=$(echo "$VERSION" | grep -oP '(?<=-).*' || echo "")

cat > "$OUTPUT_FILE" << EOF
// Auto-generated by scripts/generate_version.sh — do not edit
#pragma once
#define DAWCAST_VERSION       "$VERSION"
#define DAWCAST_VERSION_MAJOR $MAJOR
#define DAWCAST_VERSION_MINOR $MINOR
#define DAWCAST_VERSION_PATCH $PATCH
#define DAWCAST_VERSION_SUFFIX "$SUFFIX"
EOF

echo "Generated $OUTPUT_FILE (v$VERSION)"
